LeetCode/Convert Binary Number in a Linked List to Integer

Create Convert Binary Number in a Linked List to Integer

---

LeetCode/Check if Array Is Sorted and Rotated

Create Check if Array Is Sorted and Rotated

---

LeetCode/2095. Delete the Middle Node of a Linked List

 2095. Delete the Middle Node of a Linked List

---

LeetCode/Area of largest rectangle in Histogram

Create Area of largest rectangle in Histogram

---

LeetCode/Reverse a Word In a String

Create Reverse a Word In a String

---

LeetCode/4. Median of Two Sorted Arrays

Create 4. Median of Two Sorted Arrays

---

LeetCode/2. Add Two Numbers

Create 2. Add Two Numbers

---

LeetCode/addingarray

added array in c lang..

---

LeetCode/9. Palindrome Number

Please Merge all this in the main branch

Merge in main branch

---

LeetCode/Rotate Array.cpp

Create Rotate Array.cpp

---

AtoZ Sheet Striver/Remove Duplicates from Sorted Array.cpp

Remove Duplicates from Sorted Array

Create Remove Duplicates from Sorted Array.cpp

---

LeetCode/Grid Challenge.cpp

Efficient solution for the said problem

Create Grid Challenge.cpp

---

LeetCode/Red John is Back.cpp

Create Red John is Back.cpp

---

LeetCode/Journey to the Moon.cpp

Create Journey to the Moon.cpp

---

LeetCode/Game of Two Stacks.cpp

Create Game of Two Stacks.cpp

---

LeetCode/Truck Tour.cpp

Create Truck Tour.cpp

---

LeetCode/Queens on Board.cpp

Create Queens on Board.cpp

---

LeetCode/779. K-th Symbol in Grammar.cpp

Create 779. K-th Symbol in Grammar.cpp

---

LeetCode/823. Binary Trees With Factors

823. Binary Trees With Factors

Create 823. Binary Trees With Factors

---

LeetCode/60. Permutation Sequence.cpp

Create 60. Permutation Sequence.cpp

---

LeetCode/42. Trapping Rain Water.cpp

Create 42. Trapping Rain Water.cpp

---

LeetCode/Sudoku Solver.cpp

[Sudoku Solver](https://leetcode.com/problems/sudoku-solver/)

Create Sudoku Solver.cpp

---

LeetCode/Regular Expression Matching.cpp

Create  Regular Expression Matching.cpp
